### TEST GET / WEBSITE 
GET http://localhost:8383

### TEST GET /dashboard WEBSITE 
GET http://localhost:8383/dashboard

### DATA ENDPOINT 
GET http://localhost:8383/api/data

### DATA ENDPOINT FOR ADDING 
POST http://localhost:8383/api/data
Content-Type: application/json

{
    "name": "Ram"
}

### DATA ENDPOINT FOR DELETING 
DELETE  http://localhost:8383/api/data